### ISSUE TITLE
Cancel ongoing runs of long-running workflows under a PR when new changes are pushed (OSOE-743)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#288]
This is particularly interesting for long-running workflows (project/solution builds) to reduce resource consumption, but small things add up for the shorter ones (e.g., spell-checking) as well. Example: When a commit in a PR triggers the solution build and another commit is pushed while the previous one's build is still running, we can optionally cancel the now outdated build using [concurrency groups](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency):

```yaml
concurrency:
  group: ${{ inputs.cancel-in-progress-for-this-pr == 'true' && github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.ref) || github.run_id }}
  cancel-in-progress: ${{ inputs.cancel-in-progress-for-this-pr }}

on:
  workflow_call:
    inputs:
      cancel-in-progress-for-this-pr:
        type: string
        default: 'false'
```

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-743)
